#!/bin/sh
# SPDX-FileCopyrightText: 2018-2020 Harald Sitter <sitter@kde.org>
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

exec busctl --user set-property org.kde.DistroReleaseNotifier /org/kde/DistroReleaseNotifier org.kde.DistroReleaseNotifier UseDevel b true
